### ISSUE TITLE
Mirador with OCR

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/dsu_islandora_mirador#10]
## About

Integrate OCR with Mirador viewer

## Research

* Run up the isle-dc (https://github.com/Islandora-Devops/isle-dc) with `make starter_dev`, it will install islandora stack with islandora starter site https://github.com/Islandora-Devops/islandora-starter-site 
* Check and install the Mirador viewer module: https://github.com/Islandora/islandora_mirador
* Follow instruction in the README file to setup the module: https://github.com/Islandora/islandora_mirador/blob/2.x/README.md
* [This section](https://github.com/Islandora/islandora_mirador/blob/2.x/README.md#setting-up-hocr) Setup OCR and test if the mirador can show the OCR as annotations. 

## To report

* Can we use this module for our Islandora Lite stack ?  if so, report any mods we have to make it work ?

**Comment by Natkeeran** [comment]
hocr has been deployed, and integrated into the dev and deployment.
