### ISSUE TITLE
Configure the number of Thumbnail loading 

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/dsu_islandora_mirador#12]
# About 

In https://gundagunde.digital.utsc.utoronto.ca/61220/utsc36493, when a book object has many pages, especially if pages are TIF files, it takes longer to load. 

# Objectives:

* Figure out if there is a way to set a number of Thumbnail to load in Mirador viewer, https://github.com/digitalutsc/islandora_mirador/blob/drupal_mirador/js/mirador_viewer.js#L21 
* If that works, add an option to configure the number of thumbnails to load in Mirador viewer in the Mirador module https://islandora.traefik.me/admin/config/media/mirador

**Comment by Natkeeran** [comment]
We researched quite a bit about this.  No configuration provided out of the box.
