### ISSUE TITLE
Show duplicated search results text after IIIF search

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/dsu_islandora_mirador#6]
Where https://memory.digital.utsc.utoronto.ca/61220/utsc11508?q=professor

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/7862086/207172399-6e5fff8f-1ca1-4592-9ca8-577803877560.png">

**Comment by Natkeeran** [comment]
We are not using annotation based search anymore.
